import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { createClient } from "@/utils/supabase/server";
import { prisma } from "@/lib/db";
import { OnboardingCheck } from "@/components/onboarding-check";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Check if user needs onboarding
  let needsOnboarding = false
  
  try {
    const supabase = await createClient()
    const { data: { user } } = await supabase.auth.getUser()
    
    if (user) {
      const userAccount = await prisma.userAccount.findUnique({
        where: { supabaseUid: user.id },
        select: { 
          personProfile: {
            select: { id: true }
          }
        }
      })

      needsOnboarding = !!userAccount && !userAccount.personProfile
    }
  } catch (error) {
    console.error('Error checking onboarding status:', error)
  }

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning
      >
        <OnboardingCheck needsOnboarding={needsOnboarding} />
        {children}
      </body>
    </html>
  );
}
